#!/usr/bin/env python3
"""Wrap a .cc source file in a per-side C++ namespace for the BUNDLE build.

The bundle compiles Client and Server into ONE wasm. Each side keeps its own
copy of Shared/ (Float = LerpFloat on the client, float on the server, so
their Entity / Simulation layouts differ). To prevent ODR/symbol collisions
we put every wrapped TU in either `gardn::client` or `gardn::server`.

Strategy: emit a tiny generated .cc that includes Bundle/Prologue.hh at
GLOBAL scope (so <vector> et al. land in `::std`, not `gardn::client::std`),
then opens the appropriate namespace and #includes the original .cc.

Usage: wrap_sources.py <side> <orig.cc> <out.cc> <repo_root>
  side       — "client" or "server"
  orig.cc    — repo-relative path to source
  out.cc     — output wrapped file
  repo_root  — absolute path to repo root (so the #include works regardless
               of CMAKE_CURRENT_BINARY_DIR location)
"""

import os
import sys


def main(argv):
    if len(argv) != 5:
        print("usage: wrap_sources.py <client|server> <orig.cc> <out.cc> <repo_root>", file=sys.stderr)
        return 2
    side, orig, out, repo_root = argv[1:]
    if side not in ("client", "server"):
        print(f"unknown side {side!r}", file=sys.stderr)
        return 2

    repo_root = os.path.abspath(repo_root)
    orig_abs = os.path.join(repo_root, orig) if not os.path.isabs(orig) else orig
    if not os.path.exists(orig_abs):
        print(f"missing source: {orig_abs}", file=sys.stderr)
        return 2

    os.makedirs(os.path.dirname(out), exist_ok=True)

    body = (
        "// Auto-generated by Bundle/wrap_sources.py — do not edit.\n"
        f"// Wraps {orig} for the BUNDLE build (namespace gardn::{side}).\n"
        f'#include "{repo_root}/Bundle/Prologue.hh"\n'
        f"namespace gardn::{side} {{\n"
        f'#include "{orig_abs}"\n'
        "}\n"
    )
    with open(out, "w") as f:
        f.write(body)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
